version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: clms_nginx_web
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./public:/var/www/html
    depends_on:
      - laravel_php_fpm
    networks:
      - app

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clms_laravel_php_fpm
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: clms_mysql_database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: clms_db
      MYSQL_ROOT_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
