version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: clms_nginx_web
    ports:
      - "80:80"
    volumes:
      - ./docker/ngnix/nginx.conf:/etc/nginx/custom.conf
      - ./docker/ngnix/conf.d/:/etc/nginx/conf.d/
      - ./public:/var/www/html/public
    depends_on:
      - php-fpm
    command: [ "nginx", "-g", "daemon off;", "-c", "/etc/nginx/custom.conf" ]
    networks:
      - bridge

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clms_laravel_php_fpm
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - bridge

  db:
    image: mysql:8.0
    container_name: clms_mysql_database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: clms_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bridge

volumes:
  db_data:

networks:
  bridge:
    driver: bridge
