version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: clms_mysql_database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: clms_db
      # MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root"]
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 30s

  php-fpm:
    image: kidest/back-end-backend:latest
    container_name: clms_laravel_php_fpm
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: clms_nginx_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php-fpm:
        condition: service_started

volumes:
  db_data:
